sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t sahubibh/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true sahubibh/docker-react npm run test -- --coverage
